replicaCount: 2

image:
  repository: 673457926950.dkr.ecr.ap-south-1.amazonaws.com/gitops-eks-app
  tag: "37067a4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

probes:
  liveness:
    path: /healthz
    initialDelaySeconds: 5
    periodSeconds: 10
  readiness:
    path: /healthz
    initialDelaySeconds: 3
    periodSeconds: 5

env:
  appVersion: "37067a4"
